disabled_rules: # 無効化するルール
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - type_name
  
opt_in_rules: # 有効化するルール
  - empty_count
  - force_unwrapping
  - closure_spacing

included: # チェック対象
  - GD-MangaReader/GD-MangaReader

excluded: # チェック対象外
  - Pods
  - GD-MangaReader/Pods

force_unwrapping:
  severity: warning # エラーではなく警告にする
  
line_length:
  warning: 150
  ignores_urls: true
  
function_body_length:
  warning: 100

type_body_length:
  warning: 400

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60

nesting:
  type_level:
    warning: 2
