name: GD-MangaReader
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

configFiles:
  Debug: Secrets.xcconfig
  Release: Secrets.xcconfig

settings:
  base:
    SWIFT_VERSION: "5"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    branch: main
  GoogleAPIClientForREST:
    url: https://github.com/google/google-api-objectivec-client-for-rest
    from: "3.0.0"
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation
    from: "0.9.0"
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: "8.0.0"

targets:
  GD-MangaReader:
    type: application
    platform: iOS
    sources:
      - path: GD-MangaReader
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.GD-MangaReader
        INFOPLIST_FILE: GD-MangaReader/Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
    dependencies:
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: GoogleAPIClientForREST
        product: GoogleAPIClientForREST_Drive
      - package: ZIPFoundation
      - package: Kingfisher
    info:
      path: GD-MangaReader/Info.plist
      properties:
        CFBundleDisplayName: GD-MangaReader
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIconName: AppIcon
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - $(GID_REVERSED_CLIENT_ID)
        GIDClientID: $(GID_CLIENT_ID).apps.googleusercontent.com
