name: iOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Homebrew
        uses: actions/cache@v4
        id: cache-homebrew
        with:
          path: |
            /usr/local/Cellar
            /usr/local/Homebrew
            /opt/homebrew
          key: ${{ runner.os }}-homebrew-${{ hashFiles('**/ios.yml') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-
            
      - name: Install Dependencies
        if: steps.cache-homebrew.outputs.cache-hit != 'true'
        run: brew install xcodegen swiftlint

      - name: Generate Project
        run: |
          cd GD-MangaReader
          echo "GID_CLIENT_ID = dummy_client_id" > Secrets.xcconfig
          echo "GID_REVERSED_CLIENT_ID = com.googleusercontent.apps.dummy_client_id" >> Secrets.xcconfig
          xcodegen generate
          
      - name: SwiftLint
        run: swiftlint
      - name: Build
        run: |
          cd GD-MangaReader
          xcodebuild build -scheme GD-MangaReader -project GD-MangaReader.xcodeproj -sdk iphoneos -destination 'generic/platform=iOS' CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
      - name: Test
        run: |
          cd GD-MangaReader
          xcodebuild test -scheme GD-MangaReader -project GD-MangaReader.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 16' CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
